---
version: "2.1"
services:
#
  minio-server:
    image: quay.io/minio/minio
    container_name: minio-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    volumes:
      - ${LOCVOL1}minio-server:/data
    #ports:
      #- 10900:9000
      #- 10901:9001
    restart: unless-stopped
    command: "server --console-address \":9001\" /data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m
#
#
networks:
  default:
    name: ${CONNET}
    external: true